# Generated by Django 6.0.2 on 2026-03-11 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_course_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catogory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('sub_catogory', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(upload_to='static/images/course_images'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='image',
            field=models.ImageField(upload_to='static/images/instructor_images'),
        ),
        migrations.AddField(
            model_name='course',
            name='Catogory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.catogory'),
        ),
    ]
