# Generated by Django 6.0.2 on 2026-03-11 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_catogory_alter_course_image_alter_instructor_image_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catogory',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='sub_catogory',
            new_name='sub_category',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='Catogory',
            new_name='Category',
        ),
    ]
