# Generated by Django 6.0.2 on 2026-03-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_course_image_alter_course_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='image',
            field=models.ImageField(upload_to='static/images/instructor_images'),
        ),
    ]
