# Generated by Django 6.0.2 on 2026-03-30 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_cart_favorite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
